"project_id": "526584"
"api_token": "b2a5c1c4610b9868c7b7f1ecea5a76fd1cdbc2ed14f1a7996f2df5cafaebbc1ef74560407d6f9de9"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source" : "/locales/**/*",
    "translation" : "/%two_letters_code%/%original_file_name%"
  }
]
