"project_id": "526584"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source" : "/locales/**/*",
    "translation" : "/%two_letters_code%/%original_file_name%"
  }
]
