name: caddy

on:
  workflow_dispatch:

jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: caddy
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-caddy:
    if: ${{ always() }}
    needs: delete-release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: |
          sudo apt install upx git

      - name: Build caddy
        run: |
          git clone https://github.com/dunglas/frankenphp
          cd frankenphp
          wget https://raw.githubusercontent.com/k930520/build/refs/heads/main/build.sh
          ./build.sh 
            
      - name: Release caddy
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: caddy
          files: frankenphp/dist/*
          prerelease: false
          
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repository: k930520/build
          status: completed
      
