name: caddy

on:
  workflow_dispatch:

jobs:
  delete-release:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: caddy
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-caddy:
    if: ${{ always() }}
    needs: delete-release
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: |
          git clone https://github.com/dunglas/frankenphp
          cd frankenphp
          ./build-static.sh 
