name: gopeed

on:
  workflow_dispatch:

env:
  GO_VERSION: "1.21.5"
  FLUTTER_VERSION: "3.16.3"
  
jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: gopeed
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-windows:
    if: ${{ always() }}
    needs: delete-release
    runs-on: windows-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout gopeed repo
        uses: actions/checkout@v3
        with:
          repository: GopeedLab/gopeed
          ref: main
          path: gopeed
          persist-credentials: false
          fetch-depth: 0
          
      - name: Build
        env:
          VERSION: "stable"
        run: |
          Invoke-WebRequest -Uri "https://github.com/jrsoftware/issrc/raw/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "ChineseSimplified.isl"
          mv ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages\"

          Remove-Item -Path "gopeed\pkg\rest\api.go"
          Remove-Item -Path "gopeed\pkg\rest\server.go"
          mv "build_gopeed\gopeed\pkg\rest\api.go" "gopeed\pkg\rest\api.go"
          mv "build_gopeed\gopeed\pkg\rest\server.go" "gopeed\pkg\rest\server.go"
          cd gopeed
          Remove-Item -Path "go.mod"
          Remove-Item -Path "go.sum"
          go mod init github.com/GopeedLab/gopeed
          go mod tidy
          go build -tags nosqlite -ldflags="-w -s" -buildmode=c-shared -o ui/flutter/windows/libgopeed.dll github.com/GopeedLab/gopeed/bind/desktop
          cd ui/flutter
          flutter build windows
          $mingw = "C:\Program Files\Git\mingw64\bin"
          $system = "C:\Windows\System32"
          $release = "build\windows\x64\runner\Release\"
          cp $mingw\libstdc++-6.dll $release
          cp $mingw\libgcc_s_seh-1.dll $release
          cp $mingw\libwinpthread-1.dll $release
          cp $system\msvcp140.dll $release
          cp $system\vcruntime140.dll $release
          cp $system\vcruntime140_1.dll $release

          New-Item -Path build\windows\Output -ItemType Directory
          Compress-Archive -Path "$release*" -DestinationPath "build\windows\Output\Gopeed-$env:VERSION-windows-amd64-portable.zip"

          cd build/windows
          echo @"
          ; Script generated by the Inno Setup Script Wizard.
          ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

          #define MyAppName "Gopeed"
          #define MyAppVersion "$($env:VERSION.substring(1))"
          #define MyAppPublisher "monkeyWie"
          #define MyAppURL "https://gopeed.com"
          #define MyAppExeName "gopeed.exe"

          [Setup]
          ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
          ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
          AppId={{5960F34D-1E42-402C-8C85-DE2FF24CBAE4}
          AppName={#MyAppName}
          AppVersion={#MyAppVersion}
          ;AppVerName={#MyAppName} {#MyAppVersion}
          AppPublisher={#MyAppPublisher}
          AppPublisherURL={#MyAppURL}
          AppSupportURL={#MyAppURL}
          AppUpdatesURL={#MyAppURL}
          DefaultDirName={autopf}\gopeed
          DisableProgramGroupPage=yes
          LicenseFile=..\..\..\..\LICENSE
          ; Remove the following line to run in administrative install mode (install for all users.)
          PrivilegesRequired=lowest
          OutputBaseFilename=gopeed
          SetupIconFile=..\..\assets\icon\icon.ico
          Compression=lzma
          SolidCompression=yes
          WizardStyle=modern
          LanguageDetectionMethod=uilanguage
          ShowLanguageDialog=yes

          [Languages]
          Name: "english"; MessagesFile: "compiler:Default.isl"
          Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

          [Tasks]
          Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

          [Files]
          Source: ".\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
          ; NOTE: Don't use "Flags: ignoreversion" on any shared system files

          [UninstallDelete]
          Type: filesandordirs; Name: "{app}"

          [Icons]
          Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
          Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

          [Run]
          Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
          "@ > setup.iss
          iscc.exe setup.iss
          mv "Output\gopeed.exe" "Output\Gopeed-$env:VERSION-windows-amd64.exe"
          Compress-Archive -Path "Output\Gopeed-$env:VERSION-windows-amd64.exe" -DestinationPath "Output\Gopeed-$env:VERSION-windows-amd64.zip"
          Remove-Item -Path "Output\Gopeed-$env:VERSION-windows-amd64.exe"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: gopeed
          files: gopeed/ui/flutter/build/windows/Output/*
          prerelease: false
          
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repository: k930520/build
          status: completed
