name: main

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  delete-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: hi3798
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-hi3798:
    if: ${{ always() }}
    needs: delete-release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout SDK repo
        uses: actions/checkout@v4
        with:
          repository: JasonFreeLab/HiSTBLinuxV100R005C00SPC060
          ref: main
          path: SDK
          persist-credentials: false
          fetch-depth: 0

      - name: Initialization environment
        run: |
          #cp SDK/bootargs_input.txt SDK/configs/hi3798mv100/prebuilts/emmc_bootargs.txt
          curl -L -o armv7l-linux-musleabihf-cross.tgz https://musl.cc/armv7l-linux-musleabihf-cross.tgz
          tar xf armv7l-linux-musleabihf-cross.tgz
          mv armv7l-linux-musleabihf-cross SDK/tools/linux/toolchains
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext bison flex bc zlib1g-dev libncurses5-dev lzma

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
          
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: hi3798
          files: compress/*
          prerelease: false
          
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repository: k930520/build
          status: completed
          
