name: main

on:
  workflow_dispatch:
  
jobs:
  delete-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: hi3798
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-hi3798:
    if: ${{ always() }}
    needs: delete-release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          
      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static
          curl -L -o ubuntu-base-22.04.5-base-armhf.tar.gz https://cdimage.ubuntu.com/ubuntu-base/releases/22.04/release/ubuntu-base-22.04.5-base-armhf.tar.gz
          mkdir ubuntu-rootfs
          tar -xpf ubuntu-base-22.04.5-base-armhf.tar.gz -C ubuntu-rootfs/
          chmod a+x build_hi3798/ch-mount.sh
          chmod a+x build_hi3798/mkrootfs.sh

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
          
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: hi3798
          files: compress/*
          prerelease: false
          
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repository: k930520/build
          status: completed
          
