name: tmate

on:
  workflow_dispatch:
  
jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: tmate
          github_token: ${{ secrets.MY_TOKEN }}
          delete_release: true
          repo: k930520/build

  build-hi3798:
    if: ${{ always() }}
    needs: delete-release
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y git

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
          
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: tmate
          files: compress/*
          prerelease: false
          
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          repository: k930520/build
          status: completed
          
